name: Duplex Playwright

on:
  workflow_call:
    inputs:
      pre-test:
        type: string
      test-command:
        type: string
        default: npx playwright test
      hosting-provider:
        type: string

jobs:
  local:
    uses: ./.github/workflows/run-playwright.yml
    with:
      pre-test: ${{ inputs.pre-test }}
      test-command: ${{ inputs.test-command }}
      artifact-name: playwright-test-report-local

  remote:
    uses: ./.github/workflows/run-playwright.yml
    with:
      pre-test: ${{ inputs.pre-test }}
      test-command: ${{ inputs.test-command }}
      hosting-provider: ${{ inputs.hosting-provider }}
      artifact-name: playwright-test-report-remote
