name: Run Playwright

on:
  workflow_call:
    inputs:
      pre-test:
        type: string
      test-command:
        type: string
        default: npx playwright test
      hosting-provider:
        type: string
      artifact-name:
        type: string
        default: playwright-test-report

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Pre Test
        if: ${{ inputs.pre-test }}
        run: ${{ inputs.pre-test }}

      - name: Install Playwright Dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright
        run: ${{ inputs.test-command }}
        env:
          HOSTING_PROVIDER: ${{ inputs.hosting-provider }}

      - name: Uplaod Artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: ${{ inputs.artifact-name }}
          path: test-results
