name: Run Playwright

on:
  workflow_call:
    inputs:
      pre-test:
        type: string
      test-command:
        type: string
        default: bunx playwright test
      hosting-provider:
        type: string
      artifact-name:
        type: string
        default: playwright-test-report

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - name: Install Bun
        run: bun i

      - name: Pre Test
        if: ${{ inputs.pre-test }}
        run: ${{ inputs.pre-test }}

      - name: Install Playwright Dependencies
        run: bunx playwright install --with-deps

      - name: Run Playwright
        run: ${{ inputs.test-command }}
        env:
          HOSTING_PROVIDER: ${{ inputs.hosting-provider }}

      - name: Uplaod Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ inputs.artifact-name }}
          path: test-results
