name: Run Playwright

on:
  workflow_call:
    inputs:
      pre-test:
        type: string
      test-command:
        type: string
        default: npx playwright test
      hosting-provider:
        type: string

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Pre Test
        if: ${{ inputs.pre-test }}
        run: ${{ inputs.pre-test }}

      - name: Install Playwright Dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright
        run: ${{ inputs.test-command }}
        env:
          HOSTING_PROVIDER: ${{ inputs.hosting-provider }}

      - name: Uplaod Artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: playwright-test-report
          path: test-results
